server:
  port: 19988
  servlet:
    context-path: /api/v1
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: password
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
mybatis-plus:
  global-config:
    db-config:
      id-type: ASSIGN_ID
upload:
  dir: /uploads
