server:
  port: 19988
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:mysql://192.168.233.129:3306/kmsdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

mybatis-plus:
  configuration:
    # 关键：用 StdOutImpl 直接在控制台打印 SQL + 参数
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

logging:
  level:
    # 关键：把 MyBatis / MP 调到 DEBUG
    org.mybatis: debug
    com.baomidou.mybatisplus: debug
    # 可选：看 JDBC、Hikari 的信息
    org.springframework.jdbc.core: debug
    com.zaxxer.hikari: info

upload:
  dir: /uploads
