server:
  port: 8088
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kmsdb?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
  application:
    name: kms

mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true