openapi: 3.1.0
info:
  title: 知识管理系统 API
  version: 1.0.0
  description: 后台统一接口文档（JWT，分页/排序/错误码统一约定）
servers:
  - url: http://192.168.233.129:8088/api/v1
    description: 运行在192.168.233.129上

tags:
  - name: Category # 演示资源；照此新增其它资源

paths:
  /category:
    get:
      tags: [Category]
      summary: 获取分类列表
      operationId: listCategories
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
    post:
      tags: [Category]
      summary: 创建分类
      operationId: createCategory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: boolean
    put:
      tags: [Category]
      summary: 更新分类
      operationId: updateCategory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: boolean
  /category/{id}:
    get:
      tags: [Category]
      summary: 按ID获取分类
      operationId: getCategory
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
    delete:
      tags: [Category]
      summary: 删除分类
      operationId: deleteCategory
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: boolean
  /category/batch:
    post:
      tags: [Category]
      summary: 批量创建分类
      operationId: saveCategories
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Category'
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: boolean
  /category/tree:
    get:
      tags: [Category]
      summary: 获取分类树
      operationId: categoryTree
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CategoryTree'
  /category/{id}/childrenTree:
    get:
      tags: [Category]
      summary: 获取子分类树
      operationId: childrenTree
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CategoryTree'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        parentId:
          type: integer
          format: int64
          nullable: true
        recommend:
          type: integer
          description: 是否推荐
        status:
          type: integer
        remark:
          type: string
          nullable: true
        createdBy:
          type: string
          nullable: true
        createdAt:
          type: string
          format: date-time
          nullable: true
        updatedAt:
          type: string
          format: date-time
          nullable: true
    CategoryTree:
      type: object
      properties:
        id:
          type: integer
          format: int64
        label:
          type: string
        parentId:
          type: integer
          format: int64
          nullable: true
        recommend:
          type: integer
        status:
          type: integer
        children:
          type: array
          items:
            $ref: '#/components/schemas/CategoryTree'

security:
  - bearerAuth: []
